---
abstract: 'A simple blackboard database and dispatcher.'
author:
  - unknown
build_requires:
  BSD::Resource: 0
  Devel::Leak: 0
  EV: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Blackboard
provides:
  Async::Blackboard:
    file: lib/Async/Blackboard.pm
    version: v0.3.6
requires:
  Mouse: 0
  Scalar::Util: 0
version: v0.3.6
